# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bookscan}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yoshihiro TAKAHARA"]
  s.date = %q{2011-01-19}
  s.default_executable = %q{bookscan}
  s.description = %q{This is a scraper of Bookscan (http://www.bookscan.co.jp) Service.This is *NOT* a official software of Bookscan.}
  s.email = %q{y.takahara@gmail.com}
  s.executables = ["bookscan"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/bookscan",
    "bookscan.gemspec",
    "lib/bookscan.rb",
    "lib/bookscan/agent.rb",
    "lib/bookscan/book.rb",
    "lib/bookscan/cache.rb",
    "lib/bookscan/cli.rb",
    "lib/bookscan/commands.rb",
    "lib/bookscan/group.rb",
    "lib/bookscan/groups.rb",
    "test/helper.rb",
    "test/test_bookscan.rb"
  ]
  s.homepage = %q{http://github.com/tumf/bookscan}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{BookScan Scraper}
  s.test_files = [
    "test/helper.rb",
    "test/test_bookscan.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<mutter>, [">= 0"])
      s.add_runtime_dependency(%q<keystorage>, ["> 0.1"])
      s.add_runtime_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<highline>, ["> 1.6"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<mutter>, [">= 0"])
      s.add_dependency(%q<keystorage>, ["> 0.1"])
      s.add_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_dependency(%q<highline>, ["> 1.6"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<mutter>, [">= 0"])
    s.add_dependency(%q<keystorage>, ["> 0.1"])
    s.add_dependency(%q<mechanize>, [">= 1.0.0"])
    s.add_dependency(%q<highline>, ["> 1.6"])
  end
end

